"""add user and verification table

Revision ID: 60120c878df4
Revises: 
Create Date: 2022-04-18 22:34:29.370137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60120c878df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('birth', sa.Date(), nullable=False),
    sa.Column('locale', sa.String(length=128), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_table('verification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('auth_code', sa.String(length=6), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('auth_expired_time', sa.DateTime(), nullable=False),
    sa.Column('join_expired_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification')
    op.drop_table('user')
    # ### end Alembic commands ###
